version: "latest"

services:
  exp-book-mysql:
    image: roamgunner/exp-book-mysql
    ports:
      - 3307:3306
    volumes:
      - eb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: experience_book
    networks:
      eb-net:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -P 3306 -u root --password=123456789"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  exp-book-server:
    image: roamgunner/exp-book-server
    networks:
      eb-net:
    ports:
      - 3100:3000
    volumes:
      - eb-serevr-uploads:/app/uploads/
    working_dir: /app
    environment:
      MYSQL_HOST: exp-book-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DB: experience_book
    command: sh -c "npm install && npm run prod"
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      exp-book-mysql:
        condition: service_healthy

  exp-book-vue3-web:
    image: roamgunner/exp-book-vue3-web
    networks:
      eb-net:
    ports:
      - 8100:80
    depends_on:
      exp-book-server:
        condition: service_healthy

networks:
  eb-net:


volumes:
  eb-data:
  eb-serevr-uploads: