version: "latest"

services:
  exp-book-mysql:
    image: roamgunner/exp-book-mysql
    ports:
      - 3307:3306
    volumes:
      - eb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: experience_book
    networks:
      eb-net:


  exp-book-server:
    image: roamgunner/exp-book-server
    depends_on:
      - exp-book-mysql
    networks:
      eb-net:
    ports:
      - 3100:3000
    volumes:
      - eb-serevr-uploads:/app/uploads/
    working_dir: /app
    environment:
      MYSQL_HOST: exp-book-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DB: experience_book
    command: sh -c "npm install && npm run prod"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h exp-book-mysql -u root -p 123456789"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  exp-book-vue3-web:
    image: roamgunner/exp-book-vue3-web
    depends_on:
      - exp-book-mysql
      - exp-book-server
    networks:
      eb-net:
    ports:
      - 8100:80
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://exp-book-server:3000/common/healthcheck"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  eb-net:


volumes:
  eb-data:
  eb-serevr-uploads: